name: Issue-based Dev/Prod existent image deploy 

on:
  issues:
    types: 
      - opened
      - edited
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract variables
        id: extract_variables
        run: |
          # Extracting variables from issue body
          ISSUE_BODY="${{ github.event.issue.body }}"
          ENV=$(echo "$ISSUE_BODY" | grep -o -- '--env [^ ]*' | cut -d' ' -f2)
          TAG=$(echo "$ISSUE_BODY" | grep -o -- '--tag [^ ]*' | cut -d' ' -f2)

          echo "::set-output name=env::$ENV"
          echo "::set-output name=tag::$TAG"

      - name: Use variables in workflow
        run: |
          ENVIRONMENT="${{ steps.extract_variables.outputs.env }}"
          TAG_VERSION="${{ steps.extract_variables.outputs.tag }}"

          echo "Environment: $ENVIRONMENT"
          echo "Tag Version: $TAG_VERSION"
