name: Issue-based Dev/Prod existent image deploy 

on:
  issues:
    types: 
      - opened
jobs:
  parse_issue_body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Parse issue body
        id: parse_body
        run: |
          # Extract variable values from the issue body
          TAG=$(echo "${{ github.event.issue.body }}" | grep -o 'tag: \K.*')
          ENV=$(echo "${{ github.event.issue.body }}" | grep -o 'env: \K.*')

          echo "::set-output name=tag::$TAG"
          echo "::set-output name=env::$ENV"
