name: Issue-based Dev/Prod existent image deploy 

on:
  issues:
    types: 
      - opened
      - edited
      
  issue_comment:
     types: 
       - created
jobs:
  extract-context:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.extract_variables.outputs.environment }}
      tag_img: ${{ steps.extract_variables.outputs.tag_img }}
    steps:
      - name: Extract variables
        id: extract_variables
        run: |
          # Extracting variables from issue body
          ISSUE_BODY="${{ github.event.issue.body }}"
          ENV=$(echo "$ISSUE_BODY" | grep -o -- '--env [^ ]*' | cut -d' ' -f2)
          TAG=$(echo "$ISSUE_BODY" | grep -o -- '--tag [^ ]*' | cut -d' ' -f2)

          "environment=${ ENV }" >> "$GITHUB_OUTPUT"
          "tag_img=${ TAG }" >> "$GITHUB_OUTPUT"
          
          if [ "${ ENV }" == "dev" ]; then
            "tag_img=dev-${ TAG }" >> "$GITHUB_OUTPUT"
          fi
          echo "env: ${ environment }"
          echo "tag_img: ${ tag_img }"
  build:
    runs-on: ubuntu-latest
    needs: [extract-context]
    steps:
      - env:
          ENV: ${{needs.extract-context.outputs.environment}}
          TAG: ${{needs.extract-context.outputs.tag_img}}
        name: Build selected image
        run: |
          echo "$OUTPUT1 $OUTPUT2"


