name: Issue-based Dev/Prod existent image deploy 

on:
  issues:
    types: 
      - opened
      - edited
      
  issue_comment:
     types: 
       - created
jobs:
  extract-context:
    runs-on: ubuntu-latest
    steps:
      - name: Extract variables
        id: extract_variables
        run: |
          # Extracting variables from issue body
          ISSUE_BODY="${{ github.event.issue.body }}"
          ENV=$(echo "$ISSUE_BODY" | grep -o -- '--env [^ ]*' | cut -d' ' -f2)
          TAG=$(echo "$ISSUE_BODY" | grep -o -- '--tag [^ ]*' | cut -d' ' -f2)

          echo "::set-output name=env::$ENV"
          echo "::set-output name=tag::$TAG"

      - name: Use variables in workflow
        run: |
          ENVIRONMENT="${{ steps.extract_variables.outputs.env }}"

          if [ "${ENVIRONMENT}" == "dev"]; then
            TAG_IMAGE="dev-${{ steps.extract_variables.outputs.tag }}"
          else
            TAG_IMAGE="${{ steps.extract_variables.outputs.tag }}"
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build selected image
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "Tag Version: $TAG_IMAGE"
