name: Issue-based Dev/Prod existent image deploy 

on:
  issues:
    types: 
      - opened
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      deploy_target:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
        run: echo "Deploying build:${{ inputs.env }} to target:${{ inputs.deploy_target }}"
          echo "::set-output name=env::$ENV"
